### ISSUE TITLE
Dying in the Treasure Chest Game after opening a door lets you cheese the minigame

### ISSUE THREAD

**Issue by ETR-BTF** [TestRunnerSRL/OoT-Randomizer#1663] opened 2022-08-09 22:22 UTC
While this is (presumably) a vanilla bug, I don't think it was accessible until bonko (= OHKO bonks) was added. For that reason I am not sure if this should be classified as a rando bug to be fixed. If it's decided to not remove/fix this, then should it be part of logic? A fix should keep in mind to not patch the Ocarina Items glitch for cheesing this minigame.

**Comment by ETR-BTF** [comment] 2022-08-09 22:25
From discord:

> Copying a question over from rsl-discussion for visibility. 
With the new one bonk KO setting (if you bonk you die) you can die in places that you historically could not. This includes the treasure chest minigame. Dying in here resets links position to the front of the game, allows you to purchase a new key from the dude but apparently keeps the doors unlocked.

**Comment by ETR-BTF** [comment] 2022-08-09 22:27
Also worth mentioning: you can also die in there thru Ice Traps in Multiworlds. Is that something we want to keep also?

**Comment by TreZc0** [comment] 2022-08-09 22:56
As mentioned in the racemod-general discussion, this is clearly a bug not originally intended. Unlike OI usage here, this is not a bug possible in the original game, but one that was made possible through a rando feature implementation.

Should be fixed, either by disabling bonk damage in treasure chest game or in other ways that do not harm the OI trick useful in glitched rulesets.

**Comment by fenhl** [comment] 2022-08-10 06:47
While disabling bonk damage could potentially be a quick fix, it doesn't address ice traps, and it also removes the option to deathwarp back to the front from the final room. A better fix might be to make the doors reset themselves if you die (but not if you play Sun's). If that's not doable, ice traps could be handled separately by adding a new condition to the check for whether ice traps can be applied.

**Closed** 2022-08-18 23:00 UTC
