### ISSUE TITLE
Overlapping collection of Prelude and ToT Reward from Rauru

### ISSUE THREAD

**Issue by alkalineace** [TestRunnerSRL/OoT-Randomizer#2247] opened 2024-06-11 18:12 UTC
If the ToT Reward from Rauru check is the second medaillon required for the LACS check and the Prelude check has not been claimed yet, their collection can be overlapped by a timed input on A.
The window is pretty tight, but I managed to get it several times.

If you succeed to reproduce this bug, you don't need to play the song to collect it.

Additionnaly, the collection of the LACS item can only be claimed after reloading the entire area again.

https://github.com/OoTRandomizer/OoT-Randomizer/assets/7566908/b4d97a40-b24d-4d32-b9e3-8214a9dc6db0

**Comment by fenhl** [comment] 2024-06-27 07:35
I'm unable to reproduce. Could you record a video of the bug using the input viewer setting please? Also, to make sure there's no misunderstanding, walking into the Master Sword chamber on this plando should reproduce the bug, right?

```json
{
    "settings": {
        "open_forest": "open",
        "starting_age": "adult",
        "open_door_of_time": true,
        "shuffle_dungeon_rewards": "anywhere",
        "starting_items": {
            "Forest Medallion": 1,
            "Shadow Medallion": 1
        }
    },
    "locations": {
        "ToT Reward from Rauru": "Spirit Medallion"
    }
}
```

**Comment by fenhl** [comment] 2024-07-16 00:10
After asking for clarification on Discord, here's a plando where I was able to reproduce the bug 2nd try:

```json
{
    "settings": {
        "open_forest": "open",
        "starting_age": "adult",
        "open_door_of_time": true,
        "empty_dungeons_mode": "count",
        "empty_dungeons_count": 8
    },
    "locations": {
        "ToT Reward from Rauru": "Spirit Medallion"
    }
}
```

**Comment by fenhl** [comment] 2024-07-16 00:25
Maybe this could be fixed by adding a condition to prevent delayed items from being given while a text box is displayed.

**Comment by fenhl** [comment] 2024-07-17 12:48
Or maybe not, or at least adding `z64_game.msgContext.textId == 0` to `link_is_ready` doesn't fix the bug.

**Comment by flagrama** [comment] 2024-07-21 16:14
What about `msgCtx->msgMode == MSGMODE_NONE`(decomp) `z64_game.msgContext.msgMode == 0`(rando)?

**Comment by fenhl** [comment] 2024-07-21 19:08
Doesn't fix it either.

**Comment by flagrama** [comment] 2024-07-22 17:26
I tried lots of things referencing when the magic meter visually updates (my favorite example of something that should only happen when nothing else is going on) and it seems like this is an issue where the ocarina mode gets disabled for a while before setting itself back up. None of the checks made on magic meter than aren't made on link_is_ready made a difference. However increasing the number of pending frames before giving an item seems to fix this.

The following is code that has not pinpointed the most appropriate value, just went with one that should definitely work (1 whole second) and the song no longer gets interrupted by getting the medallion. Hopefully this at least helps find the solution even if it isn't acceptable on its own:
```c
    if (satisfied_pending_frames >= 20) {
        satisfied_pending_frames = 0;
        return 1;
    }
```

**Comment by fenhl** [comment] 2024-07-22 19:54
Maybe we could increase the required frame count to 20 just for the Master Sword chamber for now, until we find a better fix?

**Comment by flagrama** [comment] 2024-07-22 20:39
I have tested as low as 6 working using retroarch's turbo feature now. Is there any way of this happening for other song locations? Like Saria's Song/Minuet of Forest location via warp with an already pending item?

**Comment by fenhl** [comment] 2024-07-23 11:09
Probably, unless the other song cutscenes work differently somehow. Increasing the threshold to 6 globally seems reasonable.

**Closed as completed** 2024-07-23 13:46 UTC
Labels: Type: Bug, Component: ASM/C, Component: Documentation
