### ISSUE TITLE
(Multiplayer) Wrong player numbers in some shops

### ISSUE THREAD

**Issue by TimothieGeulin** [TestRunnerSRL/OoT-Randomizer#125] opened 2018-09-13 15:46 UTC
Sometimes, the shop display player numbers that aren't what they are supposed to be:
![sans_titre_1](https://user-images.githubusercontent.com/31931443/45499438-baa4f280-b77c-11e8-9e1d-a778542fdecd.png)
Here you can see that i already have double defense so that one is obviously not mine.
I don't know if that problem is the same as the one at the fishing pool

[OoT_DNGCSHMXUCSCAYB_STREAMINGA2_W2P1_Spoiler.txt](https://github.com/TestRunnerSRL/OoT-Randomizer/files/2380025/OoT_DNGCSHMXUCSCAYB_STREAMINGA2_W2P1_Spoiler.txt)
[OoT_DNGCSHMXUCSCAYB_STREAMINGA2_W2P2_Spoiler.txt](https://github.com/TestRunnerSRL/OoT-Randomizer/files/2380026/OoT_DNGCSHMXUCSCAYB_STREAMINGA2_W2P2_Spoiler.txt)

**Comment by TestRunnerSRL** [comment] 2018-09-13 20:19
According to the log, that double defense is for Player 2. So I think the issue is that the shops are not correctly displaying the player number. I think I know how to fix this.

**Comment by TestRunnerSRL** [comment] 2018-09-14 06:58
Should be fixed in 108c1f36df5ef8575ab22015b017bd883c562281

**Closed by TestRunnerSRL** 2018-09-14 06:58 UTC
Labels: bug
