### ISSUE TITLE
More than one skulltula token in store causes softlock on purchase (shopsanity)

### ISSUE THREAD

**Issue by HughMunguz** [TestRunnerSRL/OoT-Randomizer#207] opened 2018-10-07 07:20 UTC
Collection message will repeat based on how many tokens are listed in the store after buying one of them then freezes Link in item collection pose

**Comment by TestRunnerSRL** [comment] 2018-10-07 10:40
I couldn't reproduce. Could you please provide some more info. Specifically version, seed, setting, platform, and steps to reproduce the glitch.

**Comment by TestRunnerSRL** [comment] 2018-10-11 05:37
This is probably related to a bug if you were using an older version and not related to the number of tokens in the shop. I'm going to close this for now until there's more details since it probably fixed

**Closed by TestRunnerSRL** 2018-10-11 05:37 UTC
