### ISSUE TITLE
Order of disabled locations affects seed

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#810] opened 2019-08-02 17:12 UTC
But not the settings string. This was tested on 4.13.21 since I was looking into something else at the time...

String: CJWGC2XLHJAJFTQACTCTHBJTCLAABAJGD9JLAA
Change the order of disabled locations to get a different seed.

**Comment by TestRunnerSRL** [comment] 2019-08-05 09:43
Duplicate of #801

**Closed by TestRunnerSRL** 2019-08-05 09:43 UTC
Labels: duplicate
