### ISSUE TITLE
Multi-World Generation with 'Dungeons have one major item'

### ISSUE THREAD

**Issue by friedpen** [TestRunnerSRL/OoT-Randomizer#211] opened 2018-10-09 01:15 UTC
Seems like this setting doesn't work for multi-world generation if tokensanity is enabled (All Tokens / Dungeons Only). Raises a "Fill.FillError: Unable to place unique dungeon items" error.

OoT Randomizer Version 2.20.28 f.LUM
Settings String : 94BRK7MXK4ZVN4HCEA
Seed : test

Changing settings to  have 'Tokensanity : Off' will generate fully.

**Comment by TestRunnerSRL** [comment] 2018-10-11 05:33
Duplicate of Issue #179

**Closed by TestRunnerSRL** 2018-10-11 05:33 UTC
Labels: duplicate
