### ISSUE TITLE
Unplayable seed without use of Bombchus (unset in logic)

### ISSUE THREAD

**Issue by rchrm5** [TestRunnerSRL/OoT-Randomizer#49] opened 2018-08-18 19:30 UTC
[OoT_RH6ZM4CAECUB_3UXS5RELTO_Spoiler.txt](https://github.com/TestRunnerSRL/OoT-Randomizer/files/2299821/OoT_RH6ZM4CAECUB_3UXS5RELTO_Spoiler.txt)
See the attached spoiler log. Although Bombchus are not set to affect logic, they are required to get the GS tokens in branch 5 needed for the Megaton Hammer.

**Comment by TestRunnerSRL** [comment] 2018-09-07 02:44
Closing because the spoiler log issue is a duplicate of #23

**Closed by TestRunnerSRL** 2018-09-07 02:44 UTC
