### ISSUE TITLE
Dungeon item display broken

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#961] opened 2020-01-04 14:27 UTC
Trenter Today at 9:34 AM

https://cdn.discordapp.com/attachments/476723801032491008/663008591396995073/OoT_3C491_9EJ64ODS2Z-comp-200104-141808.png

dev 5.1.37

Happens on RA (Parrellel Core)
Could reproduce it on my own PC with Bizhawk aswell.

**Comment by r0bd0g** [comment] 2020-01-04 14:29
Apparently it worked fine in v5.1.29 and earlier

**Comment by Zannick** [comment] 2020-01-05 03:45
rlbond86 traced this back to 7f890241740f2d9c4fdb63ace7b73422412803fd from #948. We are unsure why this is the case. I dumped `chests.o` to get this diff:

```diff
--- without 7f89024
+++ with 7f89024
ASM/c/chests.o:     file format elf32-bigmips                   ASM/c/chests.o:     file format elf32-bigmips


Disassembly of section .text:                                   Disassembly of section .text:

00000000 <get_chest_override_size>:                             00000000 <get_chest_override_size>:
   0:   3c020000        lui     v0,0x0                             0:   3c020000        lui     v0,0x0
   4:   8c420000        lw      v0,0(v0)                           4:   8c420000        lw      v0,0(v0)
   8:   54400003        bnezl   v0,18 <get_chest_override_siz      8:   54400003        bnezl   v0,18 <get_chest_override_siz
   c:   3c02801c        lui     v0,0x801c                          c:   3c02801c        lui     v0,0x801c
  10:   03e00008        jr      ra                                10:   03e00008        jr      ra
  14:   908201e9        lbu     v0,489(a0)                        14:   908201e9        lbu     v0,489(a0)
  18:   27bdffe0        addiu   sp,sp,-32                     |   18:   27bdffd8        addiu   sp,sp,-40
  1c:   afbf001c        sw      ra,28(sp)                     |   1c:   afbf0024        sw      ra,36(sp)
  20:   afb00018        sw      s0,24(sp)                     |   20:   afb10020        sw      s1,32(sp)
  24:   00808025        move    s0,a0                         |   24:   afb0001c        sw      s0,28(sp)
  28:   9487001c        lhu     a3,28(a0)                     |   28:   00808025        move    s0,a0
  2c:   00073943        sra     a3,a3,0x5                     |   2c:   9487001c        lhu     a3,28(a0)
  30:   30e7007f        andi    a3,a3,0x7f                    |   30:   00073943        sra     a3,a3,0x5
  34:   344284a0        ori     v0,v0,0x84a0                  |   34:   30e7007f        andi    a3,a3,0x7f
  38:   904600a5        lbu     a2,165(v0)                    |   38:   344284a0        ori     v0,v0,0x84a0
  3c:   00802825        move    a1,a0                         |   3c:   904600a5        lbu     a2,165(v0)
  40:   0c000000        jal     0 <get_chest_override_size>   |   40:   00802825        move    a1,a0
  44:   27a40010        addiu   a0,sp,16                      |   44:   0c000000        jal     0 <get_chest_override_size>
  48:   97a40014        lhu     a0,20(sp)                     |   48:   27a40010        addiu   a0,sp,16
  4c:   14800003        bnez    a0,5c <get_chest_override_siz |   4c:   97b10014        lhu     s1,20(sp)
  50:   00000000        nop                                   |   50:   16200003        bnez    s1,60 <get_chest_override_siz
  54:   10000007        b       74 <get_chest_override_size+0 |   54:   00000000        nop
  58:   920201e9        lbu     v0,489(s0)                    |   58:   1000000b        b       88 <get_chest_override_size+0
  5c:   0c000000        jal     0 <get_chest_override_size>   |   5c:   920201e9        lbu     v0,489(s0)
  60:   00000000        nop                                   |   60:   0c000000        jal     0 <get_chest_override_size>
  64:   90420007        lbu     v0,7(v0)                      |   64:   93a40017        lbu     a0,23(sp)
  68:   30420001        andi    v0,v0,0x1                     |   68:   54400004        bnezl   v0,7c <get_chest_override_siz
  6c:   54400001        bnezl   v0,74 <get_chest_override_siz |   6c:   90420007        lbu     v0,7(v0)
  70:   24020005        li      v0,5                          |   70:   0c000000        jal     0 <get_chest_override_size>
  74:   8fbf001c        lw      ra,28(sp)                     |   74:   02202025        move    a0,s1
  78:   8fb00018        lw      s0,24(sp)                     |   78:   90420007        lbu     v0,7(v0)
  7c:   03e00008        jr      ra                            |   7c:   30420001        andi    v0,v0,0x1
  80:   27bd0020        addiu   sp,sp,32                      |   80:   54400001        bnezl   v0,88 <get_chest_override_siz
                                                              |   84:   24020005        li      v0,5
00000084 <get_chest_override_color>:                          |   88:   8fbf0024        lw      ra,36(sp)
  84:   3c020000        lui     v0,0x0                        |   8c:   8fb10020        lw      s1,32(sp)
  88:   8c420000        lw      v0,0(v0)                      |   90:   8fb0001c        lw      s0,28(sp)
  8c:   54400003        bnezl   v0,9c <get_chest_override_col <
  90:   3c02801c        lui     v0,0x801c                     <
  94:   03e00008        jr      ra                                94:   03e00008        jr      ra
  98:   908201e9        lbu     v0,489(a0)                    |   98:   27bd0028        addiu   sp,sp,40
  9c:   27bdffe0        addiu   sp,sp,-32                     |
  a0:   afbf001c        sw      ra,28(sp)                     | 0000009c <get_chest_override_color>:
  a4:   afb00018        sw      s0,24(sp)                     |   9c:   3c020000        lui     v0,0x0
  a8:   00808025        move    s0,a0                         |   a0:   8c420000        lw      v0,0(v0)
  ac:   9487001c        lhu     a3,28(a0)                     |   a4:   54400003        bnezl   v0,b4 <get_chest_override_col
  b0:   00073943        sra     a3,a3,0x5                     |   a8:   3c02801c        lui     v0,0x801c
  b4:   30e7007f        andi    a3,a3,0x7f                    |   ac:   03e00008        jr      ra
  b8:   344284a0        ori     v0,v0,0x84a0                  |   b0:   908201e9        lbu     v0,489(a0)
  bc:   904600a5        lbu     a2,165(v0)                    |   b4:   27bdffd8        addiu   sp,sp,-40
  c0:   00802825        move    a1,a0                         |   b8:   afbf0024        sw      ra,36(sp)
  c4:   0c000000        jal     0 <get_chest_override_size>   |   bc:   afb10020        sw      s1,32(sp)
  c8:   27a40010        addiu   a0,sp,16                      |   c0:   afb0001c        sw      s0,28(sp)
  cc:   97a40014        lhu     a0,20(sp)                     |   c4:   00808025        move    s0,a0
  d0:   14800003        bnez    a0,e0 <get_chest_override_col |   c8:   9487001c        lhu     a3,28(a0)
  d4:   00000000        nop                                   |   cc:   00073943        sra     a3,a3,0x5
  d8:   10000005        b       f0 <get_chest_override_color+ |   d0:   30e7007f        andi    a3,a3,0x7f
  dc:   920201e9        lbu     v0,489(s0)                    |   d4:   344284a0        ori     v0,v0,0x84a0
                                                              >   d8:   904600a5        lbu     a2,165(v0)
                                                              >   dc:   00802825        move    a1,a0
  e0:   0c000000        jal     0 <get_chest_override_size>       e0:   0c000000        jal     0 <get_chest_override_size>
  e4:   00000000        nop                                   |   e4:   27a40010        addiu   a0,sp,16
  e8:   90420007        lbu     v0,7(v0)                      |   e8:   97b10014        lhu     s1,20(sp)
  ec:   30420002        andi    v0,v0,0x2                     |   ec:   16200003        bnez    s1,fc <get_chest_override_col
  f0:   8fbf001c        lw      ra,28(sp)                     |   f0:   00000000        nop
  f4:   8fb00018        lw      s0,24(sp)                     |   f4:   10000009        b       11c <get_chest_override_color
  f8:   03e00008        jr      ra                            |   f8:   920201e9        lbu     v0,489(s0)
  fc:   27bd0020        addiu   sp,sp,32                      |   fc:   0c000000        jal     0 <get_chest_override_size>
                                                              >  100:   93a40017        lbu     a0,23(sp)
                                                              >  104:   54400004        bnezl   v0,118 <get_chest_override_co
                                                              >  108:   90420007        lbu     v0,7(v0)
                                                              >  10c:   0c000000        jal     0 <get_chest_override_size>
                                                              >  110:   02202025        move    a0,s1
                                                              >  114:   90420007        lbu     v0,7(v0)
                                                              >  118:   30420002        andi    v0,v0,0x2
                                                              >  11c:   8fbf0024        lw      ra,36(sp)
                                                              >  120:   8fb10020        lw      s1,32(sp)
                                                              >  124:   8fb0001c        lw      s0,28(sp)
                                                              >  128:   03e00008        jr      ra
                                                              >  12c:   27bd0028        addiu   sp,sp,40
```
[chests1.txt](https://github.com/TestRunnerSRL/OoT-Randomizer/files/4022888/chests1.txt)
[chests2.txt](https://github.com/TestRunnerSRL/OoT-Randomizer/files/4022889/chests2.txt)

**Comment by r0bd0g** [comment] 2020-01-05 05:16
Alright now the bug is that ice traps always appear in large chests in csmc, which is still a pretty bad issue.

**Comment by Zannick** [comment] 2020-01-05 05:24
The default ice trap appearance is Major, so this will only hit people who want Ice Traps to be Junk with CSMC. The tooltip is wrong, though, I oughta fix that.

**Comment by mzxrules** [comment] 2020-01-05 06:59
the concerning thing is that the code above is likely unrelated, and a future change could cause it to resurface again.

Incidentally, GET_CHEST_OVERRIDE_SIZE_WRAPPER isn't implemented correctly. It doesn't reserve enough space on the stack for the function arguments of get_chest_override_size, but for the time being the function doesn't try to save arg a0 on the stack

**Comment by mzxrules** [comment] 2020-01-15 00:42
> :30 PM]Roman:referring back to the dungeon menu bug/crash, there is definitely something very weird going on with a part of our asm/c hacks not working properly for some reason
[2:31 PM]Roman:I was made aware a few days ago that rainbow sword trails don't work on my Dev-R branch which has quite a few additional hacks, but none that touch rainbow sword in any way
[2:32 PM]Roman:so I tested stuff and it turns out only changing the name of the rainbow_sword.c/.h files, which causes it to compile to a different position, fixes the issue
[2:34 PM]Roman:eg. changing it to a_rainbow_sword.c/a_rainbow_sword.h so it ends up first in the rom/ram, but many other positions would probably work
[2:35 PM]Roman:but now I expect something else to be broken...
[2:36 PM]Roman:fwiw the current location of rainbow_sword code on my branch, when it doesn't work, is close to where the dungeon menu code was when it broke (text_print)
[2:36 PM]Roman:so it's probably the same mysterious issue

**Comment by mzxrules** [comment] 2020-02-10 18:58
I finally found it. 

text.c, defines static variables text_end and text_buf. in the faulting build, these variables are suppose to be assigned to address 80408000, but codegen puts them at 803F8000. The problem is possibly that armips cannot see the static variables to relocate them properly. making them non-static fixes the problem, but there's probably a better way to resolve this

**Comment by mzxrules** [comment] 2020-02-21 06:01
i have written a fix for armips that in theory should work. however i discovered another bug in the build process for bundle.o; when creating gfx.o and util.o, gcc appears to be emitting relocation data in the wrong order.

    util.o:     file format elf32-bigmips
    
    RELOCATION RECORDS FOR [.text]:
    OFFSET   TYPE              VALUE 
    00000004 R_MIPS_HI16       C_HEAP
    00000008 R_MIPS_LO16       C_HEAP
    00000010 R_MIPS_LO16       heap_next
    0000002c R_MIPS_HI16       heap_next
    00000038 R_MIPS_LO16       heap_next
    00000000 R_MIPS_HI16       heap_next
    00000044 R_MIPS_LO16       heap_next
    00000058 R_MIPS_26         heap_alloc

Normally, R_MIPS_HI16 is suppose to be followed by one or more R_MIPS_LO16, making it possible to increment the immediate that R_MIPS_HI16 mutates if the corresponding R_MIPS_LO16 immediate is signed and negative.

the source for the armips fix can be found here: 
https://github.com/mzxrules/armips

**Comment by Zannick** [comment] 2020-03-02 02:05
The new build appears to fix the issue, so I've re-added the reverted commit in e783de19.

**Closed by Zannick** 2020-03-02 02:05 UTC
