### ISSUE TITLE
Pierre Automatically Activates

### ISSUE THREAD

**Issue by katherto** [TestRunnerSRL/OoT-Randomizer#358] opened 2018-12-13 15:30 UTC
In 3.8.10 single player seeds I've had this issue pop up.  Upon activating Scarecrow song Pierre will pop up automatically when you get within his song range.  You don't have to play the Scarecrow song at all.  I was able to reliably reproduce this at the two Lake Hylia locations and in Dodongo's Cavern.  Haven't checked other locations.

**Comment by r0bd0g** [comment] 2018-12-13 15:36
On the Other tab there's an option that does that. It's either called Fast Scarecrow or Start with Scarecrow's Song or something like that. If that's checked, than this sounds like intended behaviour.

**Comment by katherto** [comment] 2018-12-13 15:38
I had checked the options before submitting just to be sure.  The seed I generated does not have "Start with Scarecrow's Song" checked.  I should have noted I don't even pull out the Ocarina as the option states you should.

**Comment by phixtyseven** [comment] 2018-12-13 16:51
Settings string and seed, appo?

**Comment by katherto** [comment] 2018-12-13 16:53
Settings String: BRGBWBACAJFBCFNEQEAASBNK2DF
Seed: DAN9OM7E1T

Not sure if it makes a difference but I'm playing on Wii VC. Using the gz inject ui to create the WAD.

**Comment by phixtyseven** [comment] 2018-12-13 17:04
Hmm... Possibly. Scarecrow was just changed last night so it hasn't undergone much testing. Everything seems to be normal for me at the Lake Hylia locations on Retroarch.

**Comment by katherto** [comment] 2018-12-13 17:06
Interesting. Yeah the one other spot this ended up happening in as well was Crater. Dropped off the wall from the piece of heart location and before it voided me out Pierre popped up. Probably safe to say on my file it's going to happen in all Pierre locations. I made another seed using the same settings so I'll keep an eye on that "issue" to see if it pops up again.

**Comment by phixtyseven** [comment] 2018-12-13 17:12
Oh, hold on a sec. I misread your post. It seems you have activated Scarecrow's Song in gameplay. This makes a lot more sense. I'm thinking that Link's state could be getting set in weird circumstances like death to where the game thinks he has the ocarina out.

**Comment by katherto** [comment] 2018-12-13 17:14
Yes definitely activated Scarecrow Song through normal gameplay. First time I noticed the issue was activating as adult, taking a few steps toward adult fishing, and Pierre came out on his own without pulling the Ocarina out or playing the song I set.

**Comment by phixtyseven** [comment] 2018-12-13 17:15
Yeah, now I'm seeing what you've described. Something funny is going on with Link's state.

**Comment by Hamsda** [comment] 2018-12-14 05:01
Yeah we can't have him autospawn at all, even if the `free scarecrow` option is enabled:
Either [it memes you in water temple](https://clips.twitch.tv/UnsightlyBlightedStingrayDuDudu) or [it can even softlock you in shadow](https://clips.twitch.tv/ScrumptiousThankfulGullPraiseIt).

Don't get me wrong, the spawning of him works great now, compared to the previous versions 3.2 (or something like that) til 3.7. But having to press the ocarina when the option is enabled and still having to play the song is a must in my book.

**Comment by TestRunnerSRL** [comment] 2018-12-14 08:49
yeah pierre auto spawning was a bug. should be fixed now

**Closed by TestRunnerSRL** 2018-12-14 08:49 UTC
