### ISSUE TITLE
Scarecrows Song Bug

### ISSUE THREAD

**Issue by ChristosOwen** [TestRunnerSRL/OoT-Randomizer#921] opened 2019-11-03 18:11 UTC
In the current live web version (5.0?). 

As adult I could not teach the scarecrow the song which I played for him as child. 

Teaching song as child - https://clips.twitch.tv/ArtisticPolishedPoxTooSpicy
Trying to learn song as adult - https://clips.twitch.tv/GracefulCreativeOwlTakeNRG

As child, I played a song but messed up my usual one, so went back immediately and played a second song. Later as adult I tried playing the second song (which should have worked) but it did not work. However it didn't automatically fail but instead nothing happened until I pressed another button. So it was sort of hanging after the 8th note.

I also tried playing the first song which I overwrote but that was automatically failing (as expected). And any incorrect combination of 8 notes was also automatically failing as expected.

**Comment by flagrama** [comment] 2019-11-03 18:26
You may have created a song with 9 notes. It seems to be something that can happen if you are too fast. I know other players like SpikeVegeta have done so in the past.

**Comment by r0bd0g** [comment] 2019-11-09 22:31
#539 Possible duplicate

**Comment by Zannick** [comment] 2019-12-24 02:05
Yeah, I can kind of hear the higher note at the end of that first clip instead of the lower note.

**Comment by Zannick** [comment] 2019-12-24 02:06
Duplicate of #539

**Closed** 2019-12-24 02:06 UTC
Labels: duplicate
