### ISSUE TITLE
MQ Dondogo cavern Deku scrub not spawned

### ISSUE THREAD

**Issue by TopHatMan** [TestRunnerSRL/OoT-Randomizer#187] opened 2018-10-02 02:12 UTC
I went through MQ DC. I did a full clear and got all scrubs. I got stuck and looked at my log

this line
DC MQ Deku Scrub Deku Sticks: Small Key (Shadow Temple)
DC MQ Deku Scrub Deku Seeds: Gold Skulltulla Token
DC MQ Deku Scrub Deku Shield: Suns Song
DC MQ Deku Scrub Red Potion: Iron Boots 

Either I had 0 money and I never got sun song. I got the Iron boots and other 2 items. I swear I saw the scrub. But i never got a song and there is no scrubs left.

OoT Randomizer Version 2.20.2 f.LUM  -  Seed: 09261196-22

On closer look at log. The log does not even match up at all. I started with Kokiri Emerald. I got song of time at shop.

**Comment by r0bd0g** [comment] 2018-10-02 17:35
MQ DC Scrubs Locations:
- Sticks/Seeds - Front left alcove in the lobby.
- Shield - Alcove above the bombable staircase.
- Red Potion - Front right side hallway, the room off to the side of that room.

You need to post your settings string for us to check the log.
Does the settings string on your rom exactly match the settings string of your spoiler?
If you originally generated the rom without the spoiler, you cannot regenerate with a spoiler and have it match.

**Comment by TestRunnerSRL** [comment] 2018-10-03 10:47
It would be good if we can verify this. A scrub disappearing implies it's sharing some flag with something else, but I'm not sure atm what it would be.

**Comment by r0bd0g** [comment] 2018-10-03 16:12
It sounds to me like he generated a spoiler after-the-fact, maybe didn't have generate log ticked.

**Comment by TopHatMan** [comment] 2018-10-04 19:04
I did the scrub I felt like I did. I think the issue is the log is not accurate.  D222S9PX3LAFSEAEDA setting string here.

**Comment by TestRunnerSRL** [comment] 2018-10-05 03:44
Well, the generation will change based on your version, settings, and seed. Since the spoiler log option is part o the setting, if you generate a seed with and without it, they will be different. Also if you've updated then the generations will change

**Comment by TopHatMan** [comment] 2018-10-06 13:19
Hey I noticed if you set big poe to random , the spoiler log always says 10.

**Comment by flagrama** [comment] 2018-10-06 14:43
That's a separate issue from this one. Create a new issue for it. Also from my quick testing it just uses whatever number the slider is frozen on, not specifically 10.

**Comment by TestRunnerSRL** [comment] 2018-12-18 09:12
Because of the confusion here, this was more likely a mistake than a bug. Unless we can get some kind of reproducability, I'm going to close this

**Closed by TestRunnerSRL** 2018-12-18 09:12 UTC
Labels: bug
