### ISSUE TITLE
Playing suns song in graves/grottos softlocks (random notes?)

### ISSUE THREAD

**Issue by ETR-BTF** [TestRunnerSRL/OoT-Randomizer#1326] opened 2021-06-08 20:11 UTC
https://www.twitch.tv/videos/1050054315

https://ootrandomizer.com/seed/get?id=805082

Tested on pj64 v3.0 and RA
PJ64 save file: https://discord.com/channels/274180765816848384/438698093354156032/851913530806108220

Notable enabled settings: random notes & text rando

Softlocks in graves and grottos, but not graveyard itself. In the OW "[i]t "softlocks" the same way but then unfreezes on the wolf howl/cuckoo"

**Comment by r0bd0g** [comment] 2021-06-08 20:42
Possible duplicate of #472

**Comment by ETR-BTF** [comment] 2021-06-08 21:10
The other issue didn't have textrando on, so it seems random notes is the culprit?

**Comment by mzxrules** [comment] 2021-06-15 03:53
softlock occurs in rooms where sun's song is banned. my speculation is that the issue is that the Serenade dialog is popping up, which is suppose to then lead into a two choice textbox.

**Comment by r0bd0g** [comment] 2021-06-15 07:43
The previous seed did not have text rando, so if this is a text rando issue, we also ought to figure out what happened with that older seed as well.

**Comment by ETR-BTF** [comment] 2021-07-12 18:26
We've had 2 reported issues of Sun's Song not properly "activating" the puzzle in the MQ Spirit symphony room. Both had note shuffle on and the issue seemed very similar to this one. One of them didn't have text shuffle on, so it's probably just the random notes. The seed on which I recreated this issue had a "slow" Sun's Song. I wonder if the speed of the song affects when the text box saying "you played the song" pops up and that that's messing with the song's effect.

https://ootrandomizer.com/seed/get?id=811919

**Comment by cjohnson57** [comment] 2021-08-28 17:53
FYI: We had a very similar bug in OoT3DR from a setting that skips song replays. I don't know the specifics but it was apparently caused by Link/music staffs waiting for the sun's song light object after it was already killed. If that's the cause of this issue as well perhaps a similar fix could be applied:
https://github.com/gamestabled/OoT3D_Randomizer/pull/327/files#diff-270a5553a7db2c7b5611995c788b5db00963594ed7d5d911fccfee126b722825R67

I don't really understand what the fix does exactly, if you have more questions I can direct you to HylianFreddy.

**Comment by ETR-BTF** [comment] 2021-11-15 21:10
> We've had 2 reported issues of Sun's Song not properly "activating" the puzzle in the MQ Spirit symphony room.
Happened again. This time the song was Left, 6x Up, Left. No log available.
https://clips.twitch.tv/LachrymoseTsunderePuppyTheTarFu-v8mGaQrswas-RgmY

**Closed** 2022-02-16 07:58 UTC
