### ISSUE TITLE
Light Arrows Hinted WotH on open bridge 0 trials

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#1183] opened 2020-11-24 01:18 UTC
I believe the Ganon hint's logic is not currently working correctly?

https://cdn.discordapp.com/attachments/704998094370111538/780602266503217152/OoT_EA97B_S80K6HT0NK_Spoiler.json
https://cdn.discordapp.com/attachments/704998094370111538/780602292138410044/blind_random_settings.json

**Comment by mracsys** [comment] 2020-11-24 02:25
Leaving this here so it's not lost.

I looked briefly into the LA hint issue and quickly ended up in over my head. I can confirm the search is not able to reach the Ganondorf hint location, but I don't know where to look further. I inspected the region objects in `search.state_list[0].world.regions` with a breakpoint in `can_reach_stone` after `max_explore` is called and noticed the rule for GC -> Tower entrance doesn't appear to be parsed (other trial entrances are `'True'`, the tower entrance still has the full rule in it), but I don't know if that means anything.

**Comment by Star1468** [comment] 2020-11-24 02:57
I'll note in here as well that it's unrelated to the bug with LAs hints earlier in the week with random settings multiworld, replicated the WOTH lights hint on 5.2.127 latest dev as well.

**Comment by Zannick** [comment] 2020-11-24 05:44
Is 5.2.117 R-1 based on 5.2.117? If so, this may already be fixed in 5.2.126.

**Comment by Zannick** [comment] 2020-11-24 05:51
@Star1468 can I get a replication in 5.2.127?

**Comment by Zannick** [comment] 2020-11-24 06:14
Okay, this seed has settings `"all_reachable": false` and `"hints": "mask"` which means `can_reach_stone` will fail because even on Ganondorf because it always asks for `guarantee_hint` (i.e. for Ganondorf it will always check whether adult can reach him with the mask of truth).

That could probably be skipped for things that aren't *really* Gossip Stones.

**Comment by r0bd0g** [comment] 2020-11-24 09:49
In this particular seed, mask of truth was reachable. So it was just the fact that it was checking that the mask was wearable as child while you speak to Ganondorf. Stone of Agony hints could be busted as well with ALR off, but it would require the SoA to be on a reachable but forever out of logic location, in order to actually be able to read a hint that was busted in this way.

**Closed** 2020-11-24 19:59 UTC
