### ISSUE TITLE
Spoiler Log not showing beatable. Ends at "Playthrough" stage #4. Missing Triforce stage.

### ISSUE THREAD

**Issue by 1215drew** [TestRunnerSRL/OoT-Randomizer#641] opened 2019-04-05 05:53 UTC
I generated this Seed with the Python client version: 4.9.3
Nearly fully randomized including entrances set to "Interiors"

Spoiler Log is attached. Pretty much as the title says. The Playthrough section ends at Stage 4 and doesn't go further on.

[OoT_B8E04_ZXKZ8TRM5V_Spoiler.txt](https://github.com/TestRunnerSRL/OoT-Randomizer/files/3046523/OoT_B8E04_ZXKZ8TRM5V_Spoiler.txt)

Also, I am stuck at about that stage in the run as well and Its feeling like its not beatable.
From looking at the spoiler log it looks like Song of Time is in Spirit Temple child side, but Requiem of Spirit is in Forest Temple. I'm wondering if this is just broken logic reflected by the lack of a completed playthrough section, or if there is something else at play here.

**Comment by DatXFire** [comment] 2019-04-05 05:55
Duplicate of #638 and fixed pending #635

**Comment by Zannick** [comment] 2019-04-05 06:02
As far as I understand the issue here, most of the playthrough issues come from the algorithm thinking some locations are unreachable or failing to take reachability into account; the seed should still be beatable (you don't need Song of Time to complete Forest, though you'll need Bottle with Letter to get there. You need Song of Storms for Bottom of the Well entrance as child which is your Spirit Temple. I don't see any blockers for those.)

**Comment by 1215drew** [comment] 2019-04-05 06:05
You're right on that!
Once I got out of gaming mode into "this seems broken mode" I forgot to
account for the entrance sanitiy when looking at the logic :P

**Comment by TestRunnerSRL** [comment] 2019-04-05 19:58
Fixed in 4.9.4

**Closed by TestRunnerSRL** 2019-04-05 19:58 UTC
