### ISSUE TITLE
Suggestion: Completely disable item shuffling

### ISSUE THREAD

**Issue by aplumafreak500** [TestRunnerSRL/OoT-Randomizer#190] opened 2018-10-02 18:51 UTC
This would allow Text Shuffling and other minor patches to be applied while disabling other randomizer features, for example, to have a (mostly) vanilla playthrough.

**Comment by TestRunnerSRL** [comment] 2018-10-03 01:35
I get this (and plando) requested a lot. Something that won't happen before 3.0, but is eventually planned I guess. I will mention there is a practice hack available that accomplishes much of what you're asking for already.

**Comment by r0bd0g** [comment] 2018-10-03 03:14
Is there an MQ practice ROM?

**Comment by TestRunnerSRL** [comment] 2018-10-03 06:14
I don't believe so.

**Comment by TestRunnerSRL** [comment] 2018-10-03 10:40
This is also a duplicate of #89

**Closed by TestRunnerSRL** 2018-10-03 10:40 UTC
Labels: duplicate, enhancement
