### ISSUE TITLE
Scarecrow doesn't recognize song in memory after reset(?)

### ISSUE THREAD

**Issue by Charles445** [TestRunnerSRL/OoT-Randomizer#150] opened 2018-09-18 19:29 UTC
I played a song for the scarecrow as child, did other things and saved + game reset, played it for him as adult and he didn't recognize it.
Infuriatingly, if I play the song away from him, it plays as it should. It's clearly still part of memory.

Going child, playing a new different song, then going adult and playing it for him without resetting worked, so I *think* it had to do with the game reset in between.

Settings: ZJ2GK9SLAX652DEA
Seed: D23KROTUE
Version: 2.18.7 f.LUM

I can provide the sra file if needed.

Here's some pictures of what I mean (please excuse the screenshot button spam!)

The notes falling because the song was rejected
![the_legend_of_zelda-033](https://user-images.githubusercontent.com/1569981/45711249-949d9a80-bb4e-11e8-8967-9f39729dc947.png)

Playing the same notes away from the scarecrow
![the_legend_of_zelda-034](https://user-images.githubusercontent.com/1569981/45711284-aed77880-bb4e-11e8-8052-8a9e58eac944.png)

**Comment by TestRunnerSRL** [comment] 2018-09-20 02:51
I wasn't able to reproduce this myself, but there might be something critical I missed

**Comment by Hamsda** [comment] 2018-09-20 09:13
I had this happen once months ago during one of my first rando runs, maybe still back on 1.0.
Someone said to me that it might have been me holding (or my stupid controller accidentally inputting) the analog stick in a direction. This apparently causes octave shifts for the notes and makes the songs mismatch even though you play the same A/C notes.
I have never actually tested this, just made sure that my controller doesn't input anything except the A/C buttons for child and adult scarecrow.
Maybe someone can confirm this as the source of this bug?

**Comment by r0bd0g** [comment] 2018-09-20 09:57
I tried doing that before and couldn't reproduce it.

**Comment by Hamsda** [comment] 2018-09-20 11:57
I just tested this with GZ and spun the analog stick in circles to make all kinds of weird sounds as child.
Playing the song as adult anywhere correctly brought up the "you played scarecrows song". But playing it for Pierre, you get the *denied* sound and can't summon him (or his brother or w/e) to the spots closeby.
So this is very likely the issue you were experiencing @Charles445

**Comment by r0bd0g** [comment] 2018-09-20 13:13
Come to think of it... I couldn't get this to occur on vanilla? It may be rando-specific...

**Comment by Hamsda** [comment] 2018-09-20 13:39
I mean I tested it on US 1.0 with just GZ patched on top of it, so not rando at all, and got the "bug" on the first try.

**Comment by r0bd0g** [comment] 2018-09-20 14:00
I was on 1.2

**Comment by r0bd0g** [comment] 2018-09-20 14:07
Hamsda confirms this is a bug in vanilla 1.0

**Comment by Hamsda** [comment] 2018-09-20 14:18
Yeah just patched a US 1.2 rom with gz and tested it real quick. The octave shifting (or whatever the distorted sounds are called) are disabled for the scarecrow on 1.2. I could do them during regular ocarina play, but not when playing for Pierre. This led to him accepting my song.

So this is a bug we have in rando but it should be fixable similar to 1.0 graves I assume?
At least by someone that has more knowledge than me :P

**Comment by mzxrules** [comment] 2018-09-20 19:15
I was able to trigger this in 1.0, and did some black-box testing. The problem isn't necessarily that the song contains "bent" notes (the game seems to just check the base notes), but rather that the note bending can result in a saved song beginning with a rest note.

**Comment by r0bd0g** [comment] 2018-09-20 20:49
I think it'd be best if the 1.2 fix was used, not allowing you to bend notes at all when recording your song, to stay closer to how vanilla works.

**Comment by mzxrules** [comment] 2018-09-24 03:43
Written a fix for this
#167

**Comment by TestRunnerSRL** [comment] 2018-09-26 02:03
Merged into MQ branch

**Closed by TestRunnerSRL** 2018-09-26 02:03 UTC
Labels: bug
