### ISSUE TITLE
Crash: It's either the fog glitch or the transition object dependency issue

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#915] opened 2019-10-11 22:03 UTC
Tomb Rainier Yesterday at 3:35 AM
https://discordapp.com/channels/274180765816848384/476723801032491008/631699295736692748 <-- Entrance Randomizer (Market to Hyrule Castle/Bridge -> Gerudo Fortress from Wasteland) transition bug from @bluesoxswj (crashes on V3 Everdrive)

bluesoxswj Yesterday at 3:40 AM
Specifically, one was Market @ Castle -> GF @ Wasteland, and one was Market @ Bridge -> Wasteland @ DC.  Seeds were 258581 and 259061.

**Comment by flagrama** [comment] 2019-10-11 22:08
and roman's comments:
12:03 AM] Roman: yeah it's kind of a known issue with certain specific hardware but I have no idea what causes it
[12:03 AM] Roman: all I know is it's a form of fog glitch
12:06 AM] Roman: I wasn't aware it was an issue on everdrive tho, the only known problematic hardware before was retroarch with a specific mupen core
2:50 AM] Roman: ah yes I forgot to mention, it's not just market -> castle, it's any transition from market (as adult I believe)
[2:52 AM] Roman: the issue is probably not market tho, it's just the type of transition

**Comment by mzxrules** [comment] 2019-10-13 06:55
It's either the fog glitch or the transition object dependency issue. If it's the former, exiting from Market Town to Hyrule Field sets 800F1640 to 01, used for the cloudy environment in Hyrule Field. If it's the latter, I have this: https://github.com/mzxrules/Beta-Quest/commit/f8ed911ecb8819323d13a92bd7c1fdcb847946e2

**Comment by Wiimeiser** [comment] 2019-10-18 02:16
I've noticed the Market prerender appears in front of the sandstorm, at least in some cases. There may or may not be a connection, alternatively, it could be the game loading one prerender in front of the other?

**Comment by Dwood15** [comment] 2020-02-16 09:42
AFAICT fix for this will probably be to either: 

A) try and disable the filter or whatever it is that plays
B) come up with a hack that forces the market from connecting to the haunted wasteland.

**Comment by flagrama** [comment] 2020-05-18 20:30
![](https://github.trello.services/images/mini-trello-icon.png) [Wasteland Transition Leaving Market Causes Crash](https://trello.com/c/KcIcXciQ/18-wasteland-transition-leaving-market-causes-crash)

**Comment by ETR-BTF** [comment] 2021-01-13 23:48
Another report has been made about adult going through a loading zone in ER crashing on everdrive. It was this entrance:
```"ToT Entrance -> Market":                               {"region": "Kakariko Village", "from": "Graveyard"}```
Note the lack of a sandstorm effect.

Below is the spoiler log. Changed to .txt format because github doesn't like .json.

[OoT_4B0E5_UURB40Q0EJ_Spoiler.txt](https://github.com/TestRunnerSRL/OoT-Randomizer/files/5811588/OoT_4B0E5_UURB40Q0EJ_Spoiler.txt)

**Comment by DuskTheUmbreon** [comment] 2021-05-07 00:26
There's now at least two more crashes, fire temple>Wasteland and Dampe's grave to wasteland. On n64 and some versions of RA this crashes. On Bizhawk, ML64, and Dolphin it instead rapidly flashes white and black in a way that seems incredibly seizure-inducing.

[Here](https://discord.com/channels/274180765816848384/438698093354156032/840015004401008660) is a zpf that has them linked. Kokiri forest>Midos leads to fire, leaving it leads to wasteland. Kokiri forest>Saria's leads to dampe's grave, leaving also leads to wasteland.

At this point I'd honestly just recommend forcing all sandstorm-triggering entrances to be vanilla until there's an actual fix, as this is now a much bigger issue that could have real-life consequences.

**Closed** 2022-01-17 03:27 UTC
